spring:
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
      settings:
        web-allow-others: true
  #   Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:mem:devblog # H2 ?? ??
    username: sa  # H2 ?? ? ??? username ?? (??? ??? ??)
    password:  # H2 ?? ? ??? password ?? (??? ??? ??)

  jpa:
    hibernate:
      ddl-auto: update # ??????? ??? ? ??????? ????? ?? ??? ??
      
    properties:
      hibernate:
        format_sql: true # ???? query? ???
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
